# Generated by Django 3.1.2 on 2020-10-05 12:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doubtbox_homework_returnedhomework_score_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='hwfile',
            field=models.FileField(blank=True, null=True, upload_to=api.models.user_directory_path),
        ),
    ]
