# Generated by Django 3.1.2 on 2020-10-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201016_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
